baseURL = "https://granadabus.netlify.app/"
title = "Granada Bus Info"
theme = "PaperMod"

enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Bus schedules and stops in Granada Nicaragua"
  disableThemeToggle = true
 
[params.label]
icon = "/images/logo.png"
iconHeight = 100
text = ""
iconOnly = true

[params.analytics.google]
SiteVerificationTag = "8EUzVvYz94iEFCYXT-AvoerPkzyuFLSLyGdM7d0By-w"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[[menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
name = "Destinos"
url = "/#destinations"
weight = 2

[[menu.main]]
name = "Contacto"
url = "/contact/"
weight = 3

disableKinds = []

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]
